### ISSUE TITLE
Wrong owner for ~/.config directory

### ISSUE THREAD

**Issue by shiroyasha** [renderedtext/boxbox#29]
The owner is root, and this prevents some programs from properly working.
Did `chown -R vagrant:vagrant ~/.config` to fix it temporarily.

Based on the file `.config/configstore/update-notifier-npm.json`, I think this is somehow connected to npm.

**Comment by mimimalizam** [comment]
I was not able to setup `hub` until I've updated the permissions on `~/.config` (`hub` creates `~/.config/hub` file). Wanted to share it since it seems related.

**Comment by shiroyasha** [comment]
Stale. Closing.
