### ISSUE TITLE
BoxBox runs with UTC time

### ISSUE THREAD

**Issue by milica-nerlovic** [renderedtext/boxbox#3]
![screenshot 2017-11-08 16 31 52](https://user-images.githubusercontent.com/21684087/32557600-ec4868a8-c4a2-11e7-94c9-b4c0e1646fdd.png)
![screenshot 2017-11-08 16 32 02](https://user-images.githubusercontent.com/21684087/32557601-ec8d8c94-c4a2-11e7-9ef5-ec4244145779.png)

Maybe it has something to do with timezones.

**Comment by shiroyasha** [comment]
We need to add:

``` ruby
config.vm.provider "virtualbox" do |vb|
  vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
end
```

to the vagrantfile.

**Comment by milica-nerlovic** [comment]
Yes, I think Filip help me add something like this to my old devbox Vagrantfile, and I never had problems anymore.

**Comment by shiroyasha** [comment]
Yeah. Can you create a PR? :)

**Comment by milica-nerlovic** [comment]
Hm, no it's already there: https://github.com/renderedtext/boxbox/blob/master/Vagrantfile#L56

**Comment by shiroyasha** [comment]
Hmm, tough question in that case.

**Comment by shiroyasha** [comment]
@milica-nerlovic I figured out the issue. In boxbox we have UTC time.

**Comment by nikolalsvk** [comment]
Here's how I changed the timezone in my boxbox http://www.thegeekstuff.com/2010/09/change-timezone-in-linux
